version: "3"

volumes:
  db_data:
  directus_uploads:

services:
  database:
    image: postgres:alpine
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: directus
      POSTGRES_PASSWORD: directus
      POSTGRES_DB: directus
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"